auxiliary_data_dir: /data/shared/climate-data/aux
input_files:
- /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep5m26jqmd_20260330_150113/preproc/diagnostic/pr/metadata.yml
- /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep5m26jqmd_20260330_150113/preproc/diagnostic/tas/metadata.yml
- /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep5m26jqmd_20260330_150113/preproc/diagnostic/rsds/metadata.yml
log_level: info
output_file_type: png
plot_dir: /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep5m26jqmd_20260330_150113/plots/diagnostic/script
recipe: ewcrep5m26jqmd.yml
run_dir: /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep5m26jqmd_20260330_150113/run/diagnostic/script
script: script
version: 2.11.1
work_dir: /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep5m26jqmd_20260330_150113/work/diagnostic/script
