auxiliary_data_dir: /data/shared/climate-data/aux
input_files:
- /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep9khcd704_20260402_141821/preproc/diagnostic/pr/metadata.yml
- /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep9khcd704_20260402_141821/preproc/diagnostic/tas/metadata.yml
- /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep9khcd704_20260402_141821/preproc/diagnostic/rsds/metadata.yml
log_level: info
output_file_type: png
plot_dir: /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep9khcd704_20260402_141821/plots/diagnostic/script
recipe: ewcrep9khcd704.yml
run_dir: /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep9khcd704_20260402_141821/run/diagnostic/script
script: script
version: 2.11.1
work_dir: /home/group10/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrep9khcd704_20260402_141821/work/diagnostic/script
