auxiliary_data_dir: /data/shared/climate-data/aux
input_files:
- /home/group10/teaching-materials/book/exercise_journal_ann_laura/FlexTopo/esmvaltool_output/ewcrepxhmv7515_20260406_144253/preproc/diagnostic/pr/metadata.yml
- /home/group10/teaching-materials/book/exercise_journal_ann_laura/FlexTopo/esmvaltool_output/ewcrepxhmv7515_20260406_144253/preproc/diagnostic/tas/metadata.yml
- /home/group10/teaching-materials/book/exercise_journal_ann_laura/FlexTopo/esmvaltool_output/ewcrepxhmv7515_20260406_144253/preproc/diagnostic/rsds/metadata.yml
log_level: info
output_file_type: png
plot_dir: /home/group10/teaching-materials/book/exercise_journal_ann_laura/FlexTopo/esmvaltool_output/ewcrepxhmv7515_20260406_144253/plots/diagnostic/script
recipe: ewcrepxhmv7515.yml
run_dir: /home/group10/teaching-materials/book/exercise_journal_ann_laura/FlexTopo/esmvaltool_output/ewcrepxhmv7515_20260406_144253/run/diagnostic/script
script: script
version: 2.11.1
work_dir: /home/group10/teaching-materials/book/exercise_journal_ann_laura/FlexTopo/esmvaltool_output/ewcrepxhmv7515_20260406_144253/work/diagnostic/script
