auxiliary_data_dir: /data/shared/climate-data/aux
input_files:
- /home/group10/teaching-materials/book/exercise_journal_ann_laura/esmvaltool_output/ewcrepqndck0s5_20260402_151327/preproc/diagnostic/pr/metadata.yml
- /home/group10/teaching-materials/book/exercise_journal_ann_laura/esmvaltool_output/ewcrepqndck0s5_20260402_151327/preproc/diagnostic/tas/metadata.yml
- /home/group10/teaching-materials/book/exercise_journal_ann_laura/esmvaltool_output/ewcrepqndck0s5_20260402_151327/preproc/diagnostic/rsds/metadata.yml
log_level: info
output_file_type: png
plot_dir: /home/group10/teaching-materials/book/exercise_journal_ann_laura/esmvaltool_output/ewcrepqndck0s5_20260402_151327/plots/diagnostic/script
recipe: ewcrepqndck0s5.yml
run_dir: /home/group10/teaching-materials/book/exercise_journal_ann_laura/esmvaltool_output/ewcrepqndck0s5_20260402_151327/run/diagnostic/script
script: script
version: 2.11.1
work_dir: /home/group10/teaching-materials/book/exercise_journal_ann_laura/esmvaltool_output/ewcrepqndck0s5_20260402_151327/work/diagnostic/script
